// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details': string;
  'error': string;
  'form': string;
  'info': string;
  'input': string;
  'loader': string;
  'logo': string;
  'search': string;
  'window': string;
}
export const cssExports: CssExports;
export default cssExports;
