// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details': string;
  'info': string;
  'liveData': string;
  'primaryDetails': string;
  'secondaryDetails': string;
  'spotInfo': string;
  'tempInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
